import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
import {smoothstep,clamp} from './math.js';import {WeatherService} from './weather-service.js';import {PoseTracker} from './pose-tracker.js';import {FlowField,ParticleRenderer,StreamlineRenderer} from './flow-field.js';
const $=id=>document.getElementById(id), canvas=$('stage'), renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));let scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x050812,.07);let camera=new THREE.PerspectiveCamera(52,1,.1,100);let particles=new ParticleRenderer(scene,3500),streams=new StreamlineRenderer(scene),field=new FlowField(),weather=new WeatherService(),pose=new PoseTracker($('camera'));streams.group.visible=false;let mode='particle',last=performance.now(),fps=0,frames=0,lastFps=last;
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
for(const id of ['particleCount','particleSize','lineDensity','trailLength','bodyStrength','leftStrength','rightStrength','windDirection','windSpeed','humidity','transition','viscosity','noiseAmount','noiseScale','noiseSpeed','cameraDistance']){let el=$(id),o=$(id+'Out');let update=()=>{o.textContent=el.value;};el.addEventListener('input',update);update()}
function medium(){return $('mediumMode').value==='auto'?smoothstep(30,60,field.wind.humidity):+$('viscosity').value}function values(){if($('weatherMode').value==='manual')weather.target={direction:+$('windDirection').value,speed:+$('windSpeed').value,humidity:+$('humidity').value};field.wind=weather.update(dt,+$('transition').value);field.weights={body:+$('bodyStrength').value,left:+$('leftStrength').value,right:+$('rightStrength').value};field.noise={amount:+$('noiseAmount').value,scale:+$('noiseScale').value,speed:+$('noiseSpeed').value};$('viscosityOut').textContent=medium().toFixed(2);$('humidityOut').textContent=Math.round(field.wind.humidity)+'%'}
$('particle').onclick=()=>{mode='particle';particles.points.visible=true;streams.group.visible=false};$('stream').onclick=()=>{mode='stream';particles.points.visible=false;streams.group.visible=true};$('hide').onclick=()=>{$('panel').classList.toggle('hidden')};$('full').onclick=()=>document.documentElement.requestFullscreen?.();addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')$('panel').classList.toggle('hidden')});
$('particleCount').onchange=()=>particles.reset(+$('particleCount').value);for(const id of ['lineDensity','trailLength'])$(id).onchange=()=>streams.reset(+$('lineDensity').value,+$('trailLength').value);
let debug=$('debug'),ctx=debug.getContext('2d');function drawDebug(){ctx.clearRect(0,0,debug.width=innerWidth,debug.height=innerHeight);if(!$('debugToggle').checked)return;let cv=p=>({x:innerWidth/2+p.x*65,y:innerHeight/2-p.y*65});ctx.strokeStyle='#ffdd75';ctx.fillStyle='#ffdd75';for(const k of ['center','left','right']){let p=cv(pose.points[k]),v=pose.velocity[k];ctx.beginPath();ctx.arc(p.x,p.y,6,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+v.x*12,p.y-v.y*12);ctx.stroke()}ctx.fillText('mouse fallback / pose vectors',20,innerHeight-24)}
let dt=.016;async function boot(){let ok=await pose.start();$('status').textContent=ok?'CAMERA / POSE LIVE':'MOUSE FLOW FALLBACK';$('weatherMode').onchange=async()=>{if($('weatherMode').value==='auto'){try{await weather.locateAndLoad();$('status').textContent='OPEN-METEO LIVE'}catch{$('weatherMode').value='manual';$('status').textContent='WEATHER: MANUAL FALLBACK'}}};requestAnimationFrame(loop)}function loop(now){dt=Math.min(.05,(now-last)/1000);last=now;pose.update(now,dt);values();let v=medium();camera.position.z=+$('cameraDistance').value;camera.position.y=.2;particles.update(dt,field,pose,now/1000,v);streams.update(field,pose,now/1000,v);renderer.render(scene,camera);drawDebug();frames++;if(now-lastFps>500){fps=Math.round(frames*1000/(now-lastFps));$('fps').textContent=fps+' FPS';frames=0;lastFps=now}requestAnimationFrame(loop)}boot();
