const zero=()=>({x:0,y:0,z:0});
export class PoseTracker {
  constructor(video){this.video=video;this.points={center:zero(),left:zero(),right:zero()};this.velocity={center:zero(),left:zero(),right:zero()};this.landmarks=null;this.detected=false;this.cameraReady=false;this.ready=false;this.poseFps=0;this.lastPoseAt=0;this.mouse={x:0,y:0};window.addEventListener('pointermove',e=>this.mouse={x:e.clientX/innerWidth*2-1,y:1-e.clientY/innerHeight*2});}
  async startCamera(){console.log('[Camera] requesting');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});this.video.srcObject=stream;await this.video.play();this.cameraReady=true;console.log('[Camera] video playing',this.video.readyState,this.video.videoWidth,this.video.videoHeight);return true}catch(e){console.error('[Camera]',e);return false}}
  async startPose(){console.log('[Pose] loading');try{const v=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14');const f=await v.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');this.landmarker=await v.PoseLandmarker.createFromOptions(f,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task'},runningMode:'VIDEO',numPoses:1});this.ready=true;console.log('[Pose] ready');return true}catch(e){console.error('[Pose]',e);return false}}
  world(l){return{x:(.5-l.x)*5,y:(.5-l.y)*4,z:l.z*5}}
  accept(k,n,dt,visibility=1){if(visibility<.45)return;let p=this.points[k],r={x:(n.x-p.x)/dt,y:(n.y-p.y)/dt,z:(n.z-p.z)/dt},m=Math.hypot(r.x,r.y,r.z),cap=14;if(m>cap){r.x*=cap/m;r.y*=cap/m;r.z*=cap/m}let a=.28,v=this.velocity[k];this.velocity[k]={x:v.x*(1-a)+r.x*a,y:v.y*(1-a)+r.y*a,z:v.z*(1-a)+r.z*a};this.points[k]=n}
  update(now,dt){let raw=this.ready&&this.video.readyState>2?this.landmarker.detectForVideo(this.video,now).landmarks?.[0]:null;if(raw){this.landmarks=raw;this.detected=true;this.poseFps=1000/Math.max(1,now-this.lastPoseAt);this.lastPoseAt=now;let p=i=>this.world(raw[i]),a=p(11),b=p(12),h=p(23),j=p(24),c={x:(a.x+b.x+h.x+j.x)/4,y:(a.y+b.y+h.y+j.y)/4,z:(a.z+b.z+h.z+j.z)/4};this.accept('left',p(15),dt,raw[15].visibility);this.accept('right',p(16),dt,raw[16].visibility);this.accept('center',c,dt,Math.min(raw[11].visibility,raw[12].visibility,raw[23].visibility,raw[24].visibility))}else{this.detected=false;for(const k in this.velocity)for(const a in this.velocity[k])this.velocity[k][a]*=.78;if(!this.ready){this.points.right={x:this.mouse.x*2.7,y:this.mouse.y*2,z:0};this.points.left={x:-this.mouse.x*1.2,y:-this.mouse.y*1.2,z:.2};this.points.center={x:this.mouse.x*.35,y:this.mouse.y*.2,z:0}}return this}
}
