import { ParticleEngine } from './core/particle-engine.js';
import { CameraController } from './core/camera-controller.js';
import { OpticFlowRenderer } from './core/optic-flow.js';
import { setupControls } from './ui/controls.js';
import { PoseTracker } from './tracking/mediapipe-pose.js';
import { BodyAxisTracker } from './tracking/body-axis.js';
import { HandTracker } from './tracking/hand-tracking.js';
import { BodyField } from './fields/body-field.js';
import { HandField } from './fields/hand-field.js';
import { EnvironmentField } from './fields/environment-field.js';
import { WeatherService } from './weather/weather-service.js';
import { DebugOverlay } from './ui/debug-overlay.js';
import { setupCameraPreview } from './ui/camera-preview.js';
import { setupDemoSkeleton } from './ui/demo-skeleton.js';

const canvas=document.querySelector('#flow-canvas'),$=id=>document.getElementById(id);
const style=document.createElement('style');style.textContent='#tracking-panel{position:fixed;z-index:6;right:18px;top:58px;width:280px;max-height:calc(100vh - 78px);overflow:auto;padding:12px;background:#07131ddd;border:1px solid #244755;backdrop-filter:blur(9px);color:#acc2cc;font-size:11px}#tracking-panel h2{margin:0 0 8px;color:#75bfd2;font-size:12px}#tracking-panel button,#tracking-panel select{background:#0b1a24;color:#d8edf2;border:1px solid #315462;padding:6px;margin:2px;font:inherit}#tracking-panel label{display:grid;gap:3px;margin:7px 0}#tracking-panel input[type=range]{width:100%;accent-color:#69e8df}#camera-preview{position:fixed;z-index:4;right:18px;bottom:18px;width:220px;aspect-ratio:4/3;object-fit:cover;border:1px solid #69e8df;transform:scaleX(-1);background:#07131d}#camera-preview.hidden,#skeleton-canvas.hidden{display:none}#skeleton-canvas{position:fixed;inset:0;z-index:5;pointer-events:none;width:100%;height:100%}#debug-overlay{white-space:pre-wrap;color:#d7f6a0}';document.head.append(style);
const renderer=new OpticFlowRenderer(canvas),camera=new CameraController(canvas),video=$('camera-preview'),skeleton=$('skeleton-canvas'),inputs=Object.fromEntries([...document.querySelectorAll('input')].map(i=>[i.id,i]));
const previewShell=setupCameraPreview(video,skeleton,$('tracking-panel'));
const skeleton3d=setupDemoSkeleton($('tracking-panel'));
function config(){const n=id=>Number(inputs[id].value),width=renderer.width,height=renderer.height,fov=n('fov'),near=n('near'),far=Math.max(near+1,n('far'));return{width,height,near,far,fov,foeX:n('foeX'),foeY:n('foeY'),color:inputs.color.value,background:inputs.background.value,opacity:n('opacity'),size:n('size'),glow:n('glow'),focal:width/(2*Math.tan(fov*Math.PI/360))};}
const bodyAxis=new BodyAxisTracker(),hands=new HandTracker(),bodyField=new BodyField(),handField=new HandField(),environment=new EnvironmentField(),weather=new WeatherService();
const field=p=>{const a=bodyField.sample(),h=handField.sample(p),e=environment.sample(),v=Number(inputs.viscosity.value);return{x:(a.x+h.x+e.x)*(1-v),y:(a.y+h.y+e.y)*(1-v),z:(a.z+h.z+e.z)*(1-v)}};
const engine=new ParticleEngine(Number(inputs.count.value),config,camera,field),pose=new PoseTracker(video),debug=new DebugOverlay($('debug-overlay'));
window.__weatherFlow={engine,camera,config,bodyAxis,hands,bodyField,handField,pose};
let cameraStream=null,cameraState='OFF',skeletonOn=false,debugOn=true,paused=false,last=performance.now(),frames=0,lastFps=last;
function point(i){const p=pose.landmarks?.[i],r=previewShell.getBoundingClientRect();return p?{x:(inputs.mirror.checked?1-p.x:p.x)*r.width,y:p.y*r.height,visibility:p.visibility??1}:null;}
function drawSkeleton(){const dpr=devicePixelRatio||1;skeleton.width=innerWidth*dpr;skeleton.height=innerHeight*dpr;const c=skeleton.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,innerWidth,innerHeight);if(!skeletonOn||!pose.landmarks||pose.landmarks.length<33)return;const links=[[0,1],[1,2],[2,3],[3,7],[0,4],[4,5],[5,6],[6,8],[9,10],[11,12],[11,13],[13,15],[12,14],[14,16],[23,24],[11,23],[12,24],[23,25],[25,27],[24,26],[26,28]];c.lineWidth=3;c.strokeStyle='#70f0dc';for(const [a,b] of links){const p=point(a),q=point(b);if(!p||!q||p.visibility<.35||q.visibility<.35)continue;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke();}c.fillStyle='#ffe875';for(let i=0;i<33;i++){const p=point(i);if(!p||p.visibility<.35)continue;c.beginPath();c.arc(p.x,p.y,4,0,Math.PI*2);c.fill();}const head=point(0),hipL=point(23),hipR=point(24);if(head&&hipL&&hipR){const hip={x:(hipL.x+hipR.x)/2,y:(hipL.y+hipR.y)/2};c.strokeStyle='#ff78c8';c.lineWidth=4;c.beginPath();c.moveTo(head.x,head.y);c.lineTo(hip.x,hip.y);c.stroke();}for(const [i,color] of [[15,'#55aaff'],[16,'#ff9d55']]){const p=point(i);if(p){c.fillStyle=color;c.beginPath();c.arc(p.x,p.y,8,0,Math.PI*2);c.fill();}}}
async function startCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('getUserMedia is unavailable; use HTTPS or localhost');cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});video.srcObject=cameraStream;await video.play().catch(()=>{});cameraState='ON';$('display-status').textContent='CAMERA: ON · POSE: LOADING';}catch(error){cameraState='ERROR';$('display-status').textContent=`CAMERA: ERROR · ${error?.message||error} · PARTICLE: READY`;}}
function stopCamera(){cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;video.srcObject=null;cameraState='OFF';}
function bindTracking(){$('camera-start').onclick=startCamera;$('camera-toggle').onclick=stopCamera;$('mirror').onchange=()=>video.style.transform=inputs.mirror.checked?'scaleX(-1)':'none';$('camera-preview-toggle').onclick=()=>{video.classList.toggle('hidden');$('camera-preview-toggle').textContent=video.classList.contains('hidden')?'SHOW CAMERA PREVIEW':'HIDE CAMERA PREVIEW';};$('skeleton-toggle').onclick=()=>{skeletonOn=!skeletonOn;$('skeleton-toggle').textContent=skeletonOn?'SKELETON ON':'SKELETON OFF';};$('calibrate').onclick=()=>bodyAxis.calibrate();$('debug-toggle').onclick=()=>{debugOn=!debugOn;$('debug-overlay').hidden=!debugOn;};inputs['body-influence'].oninput=()=>bodyField.influence=Number(inputs['body-influence'].value);inputs['body-smoothing'].oninput=()=>bodyField.smoothing=Number(inputs['body-smoothing'].value);inputs['body-response'].oninput=()=>bodyField.response=Number(inputs['body-response'].value);inputs['left-influence'].oninput=()=>handField.leftInfluence=Number(inputs['left-influence'].value);inputs['right-influence'].oninput=()=>handField.rightInfluence=Number(inputs['right-influence'].value);inputs['hand-radius'].oninput=()=>handField.radius=Number(inputs['hand-radius'].value);inputs['vortex-strength'].oninput=()=>handField.vortexStrength=Number(inputs['vortex-strength'].value);$('wind-mode').onchange=async()=>{const mode=$('wind-mode').value;if(mode==='OFF'){environment.enabled=false;return;}if(mode==='MANUAL'){environment.enabled=true;return;}try{const wind=await weather.locateAndLoad();const rad=(wind.direction+180)*Math.PI/180;environment.vector={x:Math.sin(rad),y:0,z:Math.cos(rad)};environment.strength=wind.speed/10;environment.enabled=true;}catch(error){$('display-status').textContent=`WEATHER: ERROR · ${error?.message||error} · PARTICLE: READY`;}}}
setupControls({resetCloud:()=>engine.setCount(Number(inputs.count.value)),resetView:()=>{camera.reset();engine.setCount(Number(inputs.count.value));},togglePause:v=>paused=v});bindTracking();
async function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(renderer.resize())engine.setCount(Number(inputs.count.value));if(cameraState==='ON'&&pose.state==='IDLE')await pose.initialize();if(cameraState==='ON'&&pose.state==='READY'){const result=pose.detect(now);if(result?.worldLandmarks?.[0]){bodyAxis.update(result.worldLandmarks[0],dt);hands.update(result.worldLandmarks[0],dt);bodyField.update(bodyAxis.relative());handField.update(hands);}}if(!paused)engine.update(dt,true);canvas.dataset.visibleParticles=renderer.render(engine.particles,camera,config());drawSkeleton();frames++;if(now-lastFps>500){const fps=Math.round(frames*1000/(now-lastFps));$('fps').textContent=`${fps} FPS`;frames=0;lastFps=now;}debug.update({camera:cameraState,pose:pose.state,detected:Boolean(pose.landmarks),landmarks:pose.landmarks?.length||0,poseFps:pose.fps||0,axis:bodyAxis.current,left:hands.left,right:hands.right,error:pose.error});requestAnimationFrame(frame);}
requestAnimationFrame(frame);
